### ISSUE TITLE
Making a request to the blockcypher client

### ISSUE THREAD

**Issue by GabeDev** [inapay/blockcypher_client#4]
Upon executing the blockchain example code with both a free and paid plan from blockypher and a token these following error messages pop up.

![image](https://user-images.githubusercontent.com/30025248/77184136-beb67c80-6aa5-11ea-8e50-48865d8bbde2.png)

![image](https://user-images.githubusercontent.com/30025248/77184193-d988f100-6aa5-11ea-944a-85c2d6a0b7ee.png)

**Comment by haarts** [comment]
The first issue is familiar. This is not an issue with the code but you ran into the rate limiting of blockcypher. This happens REALLY quick if you just monitor ALL transactions. Check your blockcypher dashboard, there you'll see how many requests you have done.

For the second screenshot I really need to know what code was executed. Can you provide that?

**Comment by GabeDev** [comment]
according to blockcypher i only made a tiny amount of requests 
![image](https://user-images.githubusercontent.com/30025248/77207453-c428bc80-6acf-11ea-91b9-da64d04db486.png)

also for second screenshot is just this 

![image](https://user-images.githubusercontent.com/30025248/77207540-ffc38680-6acf-11ea-9e5e-063235268978.png)

both issues came from this piece
